### ISSUE TITLE
Build Failure - HTTP Error

### ISSUE THREAD

**Issue by joe61vette** [idaholab/presentations#6]
Error when trying to build workshop slides.  OS is Mojave v. 10.14.5.  Moose environment is that of Mojave. MOOSE updated on 6/30/19. 

$ git log
commit 3cb5b6cce9dc802e3e8d60d9d994a56f92efdd39 (HEAD -> master, origin/master)
Merge: d3c0f62728 75ca167951
Author: moosetest <bounces@inl.gov>
Date:   Fri Jun 28 20:00:56 2019 -0600

Error is:

Building Set: step01_summary (10 of 55)
  Reading content...
    Adding article title as heading: Step 1: Geometry and Diffusion
  Building content...
Traceback (most recent call last):
  File "./build.py", line 102, in <module>
    workshop(form=args.format)
  File "./build.py", line 70, in workshop
    format=kwargs.pop('format','remark'))
  File "/Users/joe/projects/presentations/blaster/base/PresentationMerger.py", line 10, in __init__
    PresentationBuilder.__init__(self, name, **kwargs)
  File "/Users/joe/projects/presentations/blaster/base/PresentationBuilder.py", line 78, in __init__
    self.warehouse.execute()
  File "/Users/joe/projects/presentations/blaster/slidesets/SlideSetWarehouse.py", line 58, in execute
    obj.build(raw)
  File "/Users/joe/projects/presentations/blaster/slidesets/RemarkSlideSet.py", line 94, in build
    slide = self.__createSlide(raw)
  File "/Users/joe/projects/presentations/blaster/slidesets/RemarkSlideSet.py", line 165, in __createSlide
    self._parseSlide(slide, raw)
  File "/Users/joe/projects/presentations/blaster/slidesets/INLDjangoWikiSet.py", line 20, in _parseSlide
    DjangoWikiSet._parseSlide(self, slide, raw)
  File "/Users/joe/projects/presentations/blaster/slidesets/RemarkSlideSet.py", line 177, in _parseSlide
    raw = slide.parse(raw)
  File "/Users/joe/projects/presentations/blaster/slides/DjangoWikiSlide.py", line 32, in parse
    markdown = RemarkSlide.parse(self, markdown)
  File "/Users/joe/projects/presentations/blaster/slides/RemarkSlide.py", line 212, in parse
    markdown = re.sub(regex, self.__subGitHubCode, markdown)
  File "/opt/moose/miniconda/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/joe/projects/presentations/blaster/slides/RemarkSlide.py", line 243, in __subGitHubCode
    response = urllib2.urlopen(url)
  File "/opt/moose/miniconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/moose/miniconda/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/opt/moose/miniconda/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/moose/miniconda/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/opt/moose/miniconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/moose/miniconda/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by aeslaughter** [comment]
We are no longer supporting this version of the workshop slides, please refer to https://mooseframework.inl.gov/workshop/#/ for the latest slides.
